### ISSUE TITLE
Problem with grafana-client 4.0.0: `TypeError: expected string or bytes-like object`

### ISSUE THREAD

**Issue by amotl** [panodata/grafana-wtf#126]
## Problem
```
E       TypeError: expected string or bytes-like object
```
-- https://github.com/panodata/grafana-wtf/actions/runs/8482124688/job/23240743427?pr=125#step:5:510

## References
- https://github.com/panodata/grafana-wtf/pull/125

## Thoughts
Maybe Niquests returns bytes, where Requests previously returned text?

/cc @Ousret

**Comment by amotl** [comment]
Thanks. Orthogonal to that: Maybe Niquests can come up with a better error message when it detects that it is processing on behalf of a corresponding object instance from `requests` instead of `niquests`. It can not be expected the other way round, but Niquests could do it we guess?

**Comment by Ousret** [comment]
Yes, you are right. Niquests will handle those cases more gracefully, I will do this asap.
Side note, grafana client is marked as "universal wheel" py2, py3 when it should not.

This section should be removed in the setup.cfg

```
[bdist_wheel]
universal = true
```

**Comment by amotl** [comment]
Thank you very much, we will run a 4.0.1 fixup release.

**Comment by Ousret** [comment]
I think so yes, a remnant from the past versions.

**Comment by amotl** [comment]
Away with it.

- GH-170
