### ISSUE TITLE
Compatibility problem with Grafana 8.3: TypeError: unhashable type: 'Munch'

### ISSUE THREAD

**Issue by IgorOhrimenko** [panodata/grafana-wtf#27]
Hello.
I run `grafana-wtf explore datasources --format=yaml` and return error:
```
2022-01-10 20:13:57,670 [grafana_wtf.core      ] INFO   : Setting up response cache to expire after 300 seconds
2022-01-10 20:13:57,673 [grafana_wtf.core      ] INFO   : Scanning dashboards
2022-01-10 20:13:57,739 [grafana_wtf.core      ] INFO   : Found 116 dashboards
  0%|                                                                                                                                                                                    | 0/116 [00:00<?, ?it/s]2022-01-10 20:13:57,745 [grafana_wtf.core      ] INFO   : Fetching dashboards in parallel with 5 concurrent requests
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 116/116 [00:01<00:00, 82.00it/s]
2022-01-10 20:13:59,159 [grafana_wtf.core      ] INFO   : Scanning datasources
2022-01-10 20:13:59,189 [grafana_wtf.core      ] INFO   : Found 21 data sources
Traceback (most recent call last):
  File "/usr/local/bin/grafana-wtf", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/grafana_wtf/commands.py", line 228, in run
    results = engine.explore_datasources()
  File "/usr/local/lib/python3.7/dist-packages/grafana_wtf/core.py", line 385, in explore_datasources
    ix = Indexer(engine=self)
  File "/usr/local/lib/python3.7/dist-packages/grafana_wtf/core.py", line 465, in __init__
    self.index()
  File "/usr/local/lib/python3.7/dist-packages/grafana_wtf/core.py", line 468, in index
    self.index_dashboards()
  File "/usr/local/lib/python3.7/dist-packages/grafana_wtf/core.py", line 496, in index_dashboards
    ds_panels = self.collect_datasource_names(dbdetails.panels)
  File "/usr/local/lib/python3.7/dist-packages/grafana_wtf/core.py", line 477, in collect_datasource_names
    return list(sorted(set(names)))
TypeError: unhashable type: 'Munch'
```
```
pip3 list
Package             Version
------------------- ---------
appdirs             1.4.4
attrs               21.4.0
cattrs              1.10.0
certifi             2021.10.8
chardet             4.0.0
charset-normalizer  2.0.10
colored             1.4.3
decorator           5.1.1
distro-info         0.21
docker              5.0.0
docopt              0.6.2
grafana-api         1.0.3
grafana-wtf         0.12.0
idna                3.3
iotop               0.6
jsonpath-rw         1.4.0
munch               2.5.0
pip                 18.1
ply                 3.11
pycurl              7.43.0.2
Pygments            2.11.2
PyGObject           3.30.4
python-apt          1.8.4.3
PyYAML              5.4.1
requests            2.27.1
requests-cache      0.9.0
setuptools          40.8.0
six                 1.16.0
tabulate            0.8.9
tqdm                4.62.3
typing-extensions   4.0.1
ufw                 0.36
unattended-upgrades 0.1
url-normalize       1.4.3
urllib3             1.26.8
websocket-client    0.59.0
wheel               0.37.1
```
```
pip3 install grafana-wtf --force
...
Collecting munch<3,>=2.5.0 (from grafana-wtf)
  Using cached https://files.pythonhosted.org/packages/cc/ab/85d8da5c9a45e072301beb37ad7f833cd344e04c817d97e0cc75681d248f/munch-2.5.0-py2.py3-none-any.whl
...
```

**Comment by amotl** [comment]
Dear Igor,

thanks for the report, we will look into it.

With kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

I am sorry that I don't see a way to reproduce this on my end. It must have something to do with the dashboard entities you are hosting within your Grafana instance and I have no idea what could go wrong there. Do you see any chance of exporting all dashboard entities, for example using the `grafana-backup` program [1], and sending them over to me by using a private channel?

With kind regards,
Andreas.

[1] https://pypi.org/project/grafana-backup/

**Comment by amotl** [comment]
Specifically, I am interested in the values of all `datasource` attributes from all dashboards. As far as I know, and the code handles it correspondingly, the possible values are always scalar, i.e. either a string expressing the data source name, or `null`.

Instead of sending me all your dashboards, you might want to run a quick `grep` command on all JSON representations after exporting them. This is an example which outlines where I am aiming at:
```
sink:grafana-wtf amo$ cat tests/grafana/dashboards/*.json | grep '"datasource"'
        "datasource": "-- Grafana --",
      "datasource": null,
      "datasource": "ldi_v2",
      "datasource": null,
      "datasource": "ldi_v2",
      "datasource": "ldi_v2",
      "datasource": "ldi_v2",
      "datasource": "ldi_v2",
      "datasource": null,
          "datasource": "ldi_v2",
          "datasource": "ldi_v2",
      "datasource": null,
      "datasource": null,
      "datasource": null,
        "datasource": "weatherbase",
        "datasource": "weatherbase",
        "datasource": "weatherbase",
        "datasource": "weatherbase",
        "datasource": "weatherbase",
```

If you can discover any anomaly here, specifically if `datasource` would contain a dictionary or a list, this would be the right spot where I am interested in. If so, it would be sweet if you could share the outcome.

**Comment by amotl** [comment]
Dear Igor,

we really would like to improve the program to make it work with your Grafana instance, as we believe other users might observe similar problems on their instances. It would be excellent if you can assist us on this matter by providing some information about specific settings of your dashboards as outlined above.

Thank you already and with kind regards,
Andreas.

**Comment by amotl** [comment]
Hi again,

at [1], I just discovered this snippet:
```json
"datasource": {
  "uid": "a4fcTGJnk",
  "type": "goshposh-metaqueries-datasource"
}
```

I understand that this is a fragment of a dashboard model instance. However, I haven't seen it before.

> If you can discover any anomaly here, specifically if `datasource` would contain a dictionary or a list, this would be the right spot where I am interested in.

Maybe Grafana 8 updated its dashboard data model that `datasource` is now an object instead of a plain string? Indeed, that would require some adjustments to the machinery of `grafana-wtf` then.

With kind regards,
Andreas.

[1] https://community.grafana.com/t/meta-query-plugin-issue-with-grafana-8-3-2/57931/10

/cc @marcusolsson, @zuchka

**Comment by amotl** [comment]
Ah I see, it looks like https://github.com/grafana/grafana/pull/23585 by @aocenas introduced the `uid` attribute on the datasource model with Grafana 7.0.0 already and https://github.com/grafana/grafana/pull/33817 by @ryantxu implemented the switchover with Grafana 8.3.0.

We probably missed that because we are still running Grafana 6.x and 7.x on our production machines and recently didn't follow Grafana's development close enough.

So, we will have to adjust `grafana-wtf` correspondingly.

**Comment by gidsi** [comment]
I'm running into the same issue using grafana 8.3.1

**Comment by amotl** [comment]
Thanks for confirming it, Timm.

### Repro
By editing and saving the test dashboard [`ldi.json`](https://github.com/panodata/grafana-wtf/blob/0.12.0/tests/grafana/dashboards/ldi.json) interactively with Grafana 8.3.1, it got updated from schema version 27 to 33. Afterwards, the values of the `datasource` attributes will have one of those shapes:

```json
"datasource": {
  "type": "influxdb",
  "uid": "PDF2762CDFF14A314"
}
```

```json
"datasource": {
  "uid": "weatherbase"
}
```

Running `grafana-wtf explore datasources` will produce the same stack trace you are observing. Now I can look into fixing this issue.


### Further notes
Please note that, if I understand that correctly, the assignment of the old datasource name to the `uid` attribute as seen with the `weatherbase` datasource above, is actually a bug, see https://github.com/grafana/grafana/issues/43097. It has been mitigated with Grafana 8.3.4 https://github.com/grafana/grafana/pull/43451, but this probably will not bring back the bogus datasource references.

While I can work around that issue with `grafana-wtf` on a syntax level, it will probably not be able to follow the reference in this case.

So, if some of your dashboards also have been upgraded from a lower schema version to version 33, you might want to check your dashboards if they would also contain such bogus entries. I would be curious about it.

**Comment by amotl** [comment]
Hi again,

compatibility with Grafana 8.3 and newer has been improved with #28 and grafana-wtf 0.13.0 was just released. Please let us know about the outcome for you.

```shell
pip install grafana-wtf --upgrade
grafana-wtf --version
grafana-wtf 0.13.0
```

With kind regards,
Andreas.

**Comment by IgorOhrimenko** [comment]
The error does not reproduce any more.
