### ISSUE TITLE
Unable to explore dashboards on Grafana 8.5.5

### ISSUE THREAD

**Issue by TaylorMutch** [panodata/grafana-wtf#36]
Just found this project and am very excited about it!

I ran into this problem when running the following:
```
grafana-wtf --grafana-url=MYGRAFANA --grafana-token=MYTOKEN explore dashboards --format=yaml
```

Stack trace:
```
Traceback (most recent call last):
  File "/Users/taylorm/.pyvenv/grafana-wtf/bin/grafana-wtf", line 8, in <module>
    sys.exit(run())
  File "/Users/taylorm/.pyvenv/grafana-wtf/lib/python3.7/site-packages/grafana_wtf/commands.py", line 243, in run
    results = engine.explore_dashboards()
  File "/Users/taylorm/.pyvenv/grafana-wtf/lib/python3.7/site-packages/grafana_wtf/core.py", line 438, in explore_dashboards
    ix = Indexer(engine=self)
  File "/Users/taylorm/.pyvenv/grafana-wtf/lib/python3.7/site-packages/grafana_wtf/core.py", line 492, in __init__
    self.index()
  File "/Users/taylorm/.pyvenv/grafana-wtf/lib/python3.7/site-packages/grafana_wtf/core.py", line 495, in index
    self.index_dashboards()
  File "/Users/taylorm/.pyvenv/grafana-wtf/lib/python3.7/site-packages/grafana_wtf/core.py", line 528, in index_dashboards
    ds_annotations = self.collect_datasource_items(dbdetails.annotations)
  File "/Users/taylorm/.pyvenv/grafana-wtf/lib/python3.7/site-packages/grafana_wtf/core.py", line 501, in collect_datasource_items
    for node in element:
TypeError: 'NoneType' object is not iterable
```

I see that we're currently not testing against 8.5 in the test matrix; I did fork this repo and run the tests against 8.5.5 and all listed python versions and the tests pass, so I'm not sure what the issue might be. Could a maintainer have a look into this issue? I can spend a bit of time digging into this issue as well.

**Comment by amotl** [comment]
Dear Taylor,

thank you for writing in. We are happy to hear you find this small tool to be useful for you.

On your report, it looks like one of the dashboards you are requesting has an empty `annotations` slot. The code probably expects it to be an empty list instead. We will have to account for that by modifying the code to be more graceful on this detail. Additionally, it will be nice to have a corresponding test case.

With kind regards,
Andreas.

**Comment by TaylorMutch** [comment]
That makes sense. I think the annotations behavior in Grafana changed recently, so I will have to take a look. Thank you, I will see if I can figure this out and if possible contribute a fix!

**Comment by amotl** [comment]
Great. There is only a single test case for now which uses the recently introduced `mkdashboard` helper function. I recommend to follow this route in order to eventually produce a dashboard with an unassigned/empty `annotations` slot where the machinery of `grafana-wtf` would choke upon.

After having the issue reproduced in such a manner, it will probably be easy to fix and we will have corresponding protection against future regressions.

https://github.com/panodata/grafana-wtf/blob/872365b3f1cbaa03b58c5a22b01b402c1fade877/tests/test_commands.py#L245-L270

**Comment by amotl** [comment]
Dear Taylor,

the patch from #38 should improve the situation. It was just released on behalf of `grafana-wtf==0.13.4`. Please tell us if that fixes the issue for you. Thank you again for the report!

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Taylor,

did you have a chance to check if the flaw you reported is gone when using the most recent release?

With kind regards,
Andreas.

**Comment by TaylorMutch** [comment]
Hello, apologies for delay. Yes I will give this a try.

**Comment by TaylorMutch** [comment]
Yes it looks like things are working now. Thank you for the fix!
