### ISSUE TITLE
Allow replace command to have dry run option

### ISSUE THREAD

**Issue by TaylorMutch** [panodata/grafana-wtf#47]
It would be excellent to simulate a dry run of a replacement when you want to perform a replacement across a large number of dashboards (like migrating datasource IDs)

**Comment by amotl** [comment]
Dear Taylor,

thank you for writing in. I absolutely agree with your proposal. Would you find the capacity to submit a corresponding patch?

With kind regards,
Andreas.

**Comment by amotl** [comment]
It looks like it was easy to add, see GH-54.

**Comment by TaylorMutch** [comment]
So fast! I would have contributed but you seem to have done it already 👏

**Comment by amotl** [comment]
Hi again. Can you test it on behalf of the main branch before I am running a new release [^1]?

[^1]: I will probably modernize some dependencies beforehand.

**Comment by amotl** [comment]
I've just released grafana-wtf 0.14.0, which includes the corresponding improvement. Let me know if that works for you.

**Comment by TaylorMutch** [comment]
Looking now - works like a charm! Case closed 🤛
