### ISSUE TITLE
Using `replace` causes dashboards to change directory

### ISSUE THREAD

**Issue by vinnyfuria** [panodata/grafana-wtf#5]
Grafana version 7.0.5
grafana-wtf version 0.9.0, python 3.8.5

When doing any replace command with grafana-wtf, the altered dashboard gets move out of its current grafana directory and moved into "General".

Running with `--debug` doesn't seem to provide more insight.

**Comment by amotl** [comment]
Dear Vinny,

> When doing any replace command with `grafana-wtf`, the altered dashboard gets moved out of its current Grafana folder and moved into "General".

Ouch. Thanks a bunch for reporting this. We will probably have to take care about properly roundtripping a specific attribute from/to the Grafana dashboard.

Maybe @cronosnull can take a look?

With kind regards,
Andreas.

**Comment by amotl** [comment]
Dear Vinny,

I wish you a happy new year!

Finally, I have been able to dedicate some time to this and indeed have been able to reproduce this flaw when roundtripping dashboard payloads through [grafana-api](https://github.com/m0nhawk/grafana_api)'s `get_dashboard()` and `update_dashboard()` methods [1].

I have elaborated about it within https://github.com/m0nhawk/grafana_api/issues/82 and have been able to come up with a mitigation at https://github.com/m0nhawk/grafana_api/issues/85.

Hopefully we will be able to fix this issue with the next release of `grafana-wtf`. Thanks again for bringing this to our attention.

With kind regards,
Andreas.

[1] https://gist.github.com/amotl/43bb89107227431802556b7bcb135578

**Comment by amotl** [comment]
Dear Vinny,

b77f90b6 resolved this and is part of version 0.10.0, which just has been published to PyPI. Enjoy!

With kind regards,
Andreas.

P.S.: Feel free to reopen or create another issue if you are still observing problems on this matter.

**Comment by vinnyfuria** [comment]
Thanks @amotl! I had been using your monkey patch for grafana_api. Appreciate you following up and closing the issue.
